name: JellyCrypt
version: "1.0"
slug: jellycrypt
description: "Encrypted Jellyfin media server with USB, gocryptfs & Web UI"
url: "https://github.com/ravenorbha/jellycrypt-addon"
startup: services
boot: auto
init: false

host_network: true

panel_icon: mdi:lock
panel_title: JellyCrypt
panel_admin: false
ingress: true
ingress_port: 8096
ingress_stream: true
watchdog: http://127.0.0.1:8096

arch:
  - amd64
  - aarch64

options:
  gocryptfs_password: changeme
  usb_mount_path: /media
  encrypted_folder: /media/encrypted
  mount_point: /media/clear

schema:
  gocryptfs_password: password
  usb_mount_path:
    type: string
  encrypted_folder:
    type: string
  mount_point:
    type: string

map:
  - media:rw
  - config:rw
  - share:rw
  - ssl:rw
  - addons:rw

usb: true
full_access: false
apparmor: true
